# Generated by Django 3.1.4 on 2021-02-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='users', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(null=True, verbose_name='شماره'),
        ),
    ]
