# Generated by Django 3.1.4 on 2021-02-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_auto_20210201_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_write', 'can write post'), ('can_edit', 'can accept and edit other posts and comments'), ('can_manage', 'can manage all content and users')]},
        ),
    ]
