# Generated by Django 3.1.4 on 2021-02-09 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0006_auto_20210208_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creadet_time',
        ),
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
