# Generated by Django 3.1.4 on 2021-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0008_auto_20210217_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='شماره'),
        ),
    ]
