# Generated by Django 3.1.4 on 2021-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_auto_20210303_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(null=True, verbose_name='شماره'),
        ),
    ]
